services:
  opustag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      # Map your local music library here. 
      # Format: /path/to/local/music:/music
      - /Volumes/Data/temp:/music
    environment:
      - PYTHONUNBUFFERED=1